repos:
    - repo: https://github.com/gitguardian/ggshield
      rev: v1.15.0
      hooks:
        - id: ggshield
          language_version: python3
          stages: [commit]
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
        - id: black
          language_version: python3.10.11
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          exclude: "alembic"