"""Make phone unique in User table

Revision ID: 00cc1d632c38
Revises: c47a35be1f62
Create Date: 2023-04-18 14:42:56.389142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00cc1d632c38"
down_revision = "c47a35be1f62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_phone", table_name="user")
    op.create_unique_constraint(None, "user", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("ix_user_phone", "user", ["phone"], unique=False)
    # ### end Alembic commands ###
