"""Add type field in notifications model

Revision ID: 0bf0780086eb
Revises: a85fafab9d88
Create Date: 2023-04-16 18:58:06.540780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0bf0780086eb"
down_revision = "a85fafab9d88"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("type", sa.String(), nullable=False))
    op.add_column("notification", sa.Column("user_id", sa.String(), nullable=True))
    op.drop_constraint(
        "notification_recipient_id_fkey", "notification", type_="foreignkey"
    )
    op.create_foreign_key(None, "notification", "user", ["user_id"], ["id"])
    op.drop_column("notification", "recipient_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column("recipient_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "notification", type_="foreignkey")
    op.create_foreign_key(
        "notification_recipient_id_fkey",
        "notification",
        "user",
        ["recipient_id"],
        ["id"],
    )
    op.drop_column("notification", "user_id")
    op.drop_column("notification", "type")
    # ### end Alembic commands ###
