"""Create UsesSessionStats model

Revision ID: 106cbc163be1
Revises: 23659a6edd21
Create Date: 2023-08-04 20:36:21.915592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "106cbc163be1"
down_revision = "23659a6edd21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usersessionstats",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("total_wins", sa.Integer(), nullable=True),
        sa.Column("total_losses", sa.Integer(), nullable=True),
        sa.Column("sessions_played", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersessionstats")
    # ### end Alembic commands ###
