"""Make answer to question unique in Answers model

Revision ID: 31e8d4d504ba
Revises: d4ea2718023f
Create Date: 2023-06-08 09:19:54.406557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31e8d4d504ba"
down_revision = "d4ea2718023f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "answers", ["question_id"])
    op.create_unique_constraint(None, "withdrawals", ["conversation_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "withdrawals", type_="unique")
    op.drop_constraint(None, "answers", type_="unique")
    # ### end Alembic commands ###
