"""Create UserAnswers Model

Revision ID: 326818579324
Revises: b181b883c17e
Create Date: 2023-07-13 13:37:49.071931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "326818579324"
down_revision = "b181b883c17e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "useranswers",
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("question_id", sa.String(), nullable=True),
        sa.Column("choice_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["choice_id"], ["choices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("useranswers")
    # ### end Alembic commands ###
