"""Create sessions model

Revision ID: 32799b7e6868
Revises: 00cc1d632c38
Create Date: 2023-05-01 18:03:09.905158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32799b7e6868"
down_revision = "00cc1d632c38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("questions", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
