"""Create pairing_range field

Revision ID: 433e797c3175
Revises: 55b709f2cb7e
Create Date: 2023-08-08 10:14:47.471502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "433e797c3175"
down_revision = "55b709f2cb7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poolsessionstats",
        sa.Column(
            "pairing_range",
            sa.Float(),
            nullable=True,
            comment="A percentage of the EWMA. Two results(or Result Nodes) are paired if their score distances is within 0 - pairing_range.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poolsessionstats", "pairing_range")
    # ### end Alembic commands ###
