"""Create DuoSession model

Revision ID: 50b54635932c
Revises: f6f0fee37586
Create Date: 2023-06-20 22:28:44.188888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50b54635932c"
down_revision = "f6f0fee37586"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duosession",
        sa.Column("party_a", sa.String(), nullable=False),
        sa.Column("party_b", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column(
            "amount",
            sa.Float(asdecimal=True, decimal_return_scale=2),
            nullable=True,
            comment="This is the Amount that was transacted.",
        ),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("winner_id", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("duosession")
    # ### end Alembic commands ###
