"""Remove DuoSession pending status

Revision ID: 51fadd36b51d
Revises: 433e797c3175
Create Date: 2023-08-10 13:47:10.971814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51fadd36b51d"
down_revision = "433e797c3175"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "poolsessionstats",
        "exp_weighted_moving_average",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="The exponential moving average of pairwise diff. of the pool",
        existing_comment="The exponential moving average of the pool",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "poolsessionstats",
        "exp_weighted_moving_average",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="The exponential moving average of the pool",
        existing_comment="The exponential moving average of pairwise diff. of the pool",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
