"""Update MpesaPayments model with new fields

Revision ID: 520d37212be6
Revises: fa9620b8ca0f
Create Date: 2023-05-12 23:37:12.704563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "520d37212be6"
down_revision = "fa9620b8ca0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesapayments",
        sa.Column(
            "result_code",
            sa.Integer(),
            nullable=True,
            comment="Indicates the status of the transaction processing. 0 means successful processing and any other code means an error occurred.",
        ),
    )
    op.add_column(
        "mpesapayments",
        sa.Column(
            "result_description",
            sa.Text(),
            nullable=True,
            comment="Description message of the Results Code.",
        ),
    )
    op.add_column(
        "mpesapayments",
        sa.Column(
            "amount",
            sa.Float(asdecimal=True, decimal_return_scale=2),
            nullable=False,
            comment="This is the Amount that was transacted.",
        ),
    )
    op.add_column(
        "mpesapayments",
        sa.Column(
            "balance",
            sa.Float(asdecimal=True, decimal_return_scale=2),
            nullable=True,
            comment="This is the Balance of the account for the short-code used.",
        ),
    )
    op.add_column(
        "mpesapayments",
        sa.Column(
            "receipt_number",
            sa.String(length=10),
            nullable=True,
            comment="This is the unique M-PESA transaction ID for the payment request.",
        ),
    )
    op.add_column(
        "mpesapayments",
        sa.Column(
            "phone_number",
            sa.String(length=25),
            nullable=False,
            comment="number of the customer who made the payment.",
        ),
    )
    op.add_column(
        "mpesapayments",
        sa.Column(
            "transaction_date",
            sa.DateTime(),
            nullable=True,
            comment="This is a timestamp that represents the date and time that the transaction completed.",
        ),
    )
    op.drop_column("mpesapayments", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesapayments",
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mpesapayments", "transaction_date")
    op.drop_column("mpesapayments", "phone_number")
    op.drop_column("mpesapayments", "receipt_number")
    op.drop_column("mpesapayments", "balance")
    op.drop_column("mpesapayments", "amount")
    op.drop_column("mpesapayments", "result_description")
    op.drop_column("mpesapayments", "result_code")
    # ### end Alembic commands ###
