"""Update total_users field to total_players

Revision ID: 55b709f2cb7e
Revises: f06c01aab65d
Create Date: 2023-08-06 00:01:04.996702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55b709f2cb7e"
down_revision = "f06c01aab65d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poolsessionstats", sa.Column("total_players", sa.Integer(), nullable=True)
    )
    op.drop_column("poolsessionstats", "total_users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poolsessionstats",
        sa.Column("total_users", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("poolsessionstats", "total_players")
    # ### end Alembic commands ###
