"""Update MpesaPayments model amount field to be nullable

Revision ID: 5674e449782f
Revises: 520d37212be6
Create Date: 2023-05-12 23:50:53.848139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5674e449782f"
down_revision = "520d37212be6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mpesapayments",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_comment="This is the Amount that was transacted.",
    )
    op.drop_column("mpesapayments", "balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesapayments",
        sa.Column(
            "balance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="This is the Balance of the account for the short-code used.",
        ),
    )
    op.alter_column(
        "mpesapayments",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_comment="This is the Amount that was transacted.",
    )
    # ### end Alembic commands ###
