"""Update account field to phone number field in MpesaPayments model

Revision ID: 6776e0bea20c
Revises: b0d3aa24b30f
Create Date: 2023-05-12 11:24:32.290809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6776e0bea20c"
down_revision = "b0d3aa24b30f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesapayments", sa.Column("phone_number", sa.String(), nullable=False)
    )
    op.drop_column("mpesapayments", "account")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesapayments",
        sa.Column("account", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("mpesapayments", "phone_number")
    # ### end Alembic commands ###
