"""Add recepient field in notifications model

Revision ID: 728c1d1372f8
Revises: 0bf0780086eb
Create Date: 2023-04-16 19:00:56.900232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "728c1d1372f8"
down_revision = "0bf0780086eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("recipient", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification", "recipient")
    # ### end Alembic commands ###
