"""Create transactions model

Revision ID: 7dee92cb908f
Revises: f48b46531332
Create Date: 2023-05-08 07:27:32.879748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7dee92cb908f"
down_revision = "f48b46531332"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("external_transaction_id", sa.String(), nullable=False),
        sa.Column(
            "initial_balance",
            sa.Numeric(),
            server_default=sa.text("0.0"),
            nullable=True,
        ),
        sa.Column(
            "final_balance", sa.Numeric(), server_default=sa.text("0.0"), nullable=True
        ),
        sa.Column("cash_flow", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("fee", sa.Numeric(), server_default=sa.text("0.0"), nullable=True),
        sa.Column("tax", sa.Numeric(), server_default=sa.text("0.0"), nullable=True),
        sa.Column("charge", sa.Numeric(), server_default=sa.text("0.0"), nullable=True),
        sa.Column("status", sa.String(), server_default="PENDING", nullable=False),
        sa.Column("service", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("external_response", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    # ### end Alembic commands ###
