"""Update PoolSessionStats model

Revision ID: ab9bff3f5f8b
Revises: 51fadd36b51d
Create Date: 2023-08-15 22:28:22.235410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab9bff3f5f8b"
down_revision = "51fadd36b51d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poolsessionstats", sa.Column("_statistics", sa.String(), nullable=True)
    )
    op.drop_column("poolsessionstats", "mean_pairwise_difference")
    op.drop_column("poolsessionstats", "exp_weighted_moving_average")
    op.drop_column("poolsessionstats", "threshold")
    op.drop_column("poolsessionstats", "pairing_range")
    op.drop_column("poolsessionstats", "average_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poolsessionstats",
        sa.Column(
            "average_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="The average of scores in the pool",
        ),
    )
    op.add_column(
        "poolsessionstats",
        sa.Column(
            "pairing_range",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="A percentage of the EWMA. Two results(or Result Nodes) are paired if their score distances is within 0 - pairing_range.",
        ),
    )
    op.add_column(
        "poolsessionstats",
        sa.Column(
            "threshold",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="The max. percentage of people who will be paired from the pool",
        ),
    )
    op.add_column(
        "poolsessionstats",
        sa.Column(
            "exp_weighted_moving_average",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="The exponential moving average of pairwise diff. of the pool",
        ),
    )
    op.add_column(
        "poolsessionstats",
        sa.Column(
            "mean_pairwise_difference",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Mean pairwise difference of the pool",
        ),
    )
    op.drop_column("poolsessionstats", "_statistics")
    # ### end Alembic commands ###
