"""Modify DuoSession status field to String type

Revision ID: b181b883c17e
Revises: 50b54635932c
Create Date: 2023-06-24 12:25:52.138116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b181b883c17e"
down_revision = "50b54635932c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("duosession_session_id_fkey", "duosession", type_="foreignkey")
    op.create_foreign_key(None, "duosession", "sessions", ["session_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "duosession", type_="foreignkey")
    op.create_foreign_key(
        "duosession_session_id_fkey", "duosession", "user", ["session_id"], ["id"]
    )
    # ### end Alembic commands ###
