"""Change recipient field to phone field

Revision ID: c47a35be1f62
Revises: 728c1d1372f8
Create Date: 2023-04-18 09:52:36.824888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c47a35be1f62"
down_revision = "728c1d1372f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("phone", sa.String(), nullable=False))
    op.drop_column("notification", "recipient")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column("recipient", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("notification", "phone")
    # ### end Alembic commands ###
