"""Update external_transaction_id field to be unique

Revision ID: d4ea2718023f
Revises: 6cb3761befa1
Create Date: 2023-05-19 20:19:08.806340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4ea2718023f"
down_revision = "6cb3761befa1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "transactions", ["external_transaction_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="unique")
    # ### end Alembic commands ###
