"""Add external_response field to MpesaPayments model

Revision ID: e4607196b3a7
Revises: 5674e449782f
Create Date: 2023-05-13 14:09:46.828368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4607196b3a7"
down_revision = "5674e449782f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mpesapayments", sa.Column("external_response", sa.JSON(), nullable=True)
    )
    op.alter_column(
        "mpesapayments",
        "phone_number",
        existing_type=sa.VARCHAR(length=25),
        comment="Phone number of the customer who made the payment.",
        existing_comment="number of the customer who made the payment.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mpesapayments",
        "phone_number",
        existing_type=sa.VARCHAR(length=25),
        comment="number of the customer who made the payment.",
        existing_comment="Phone number of the customer who made the payment.",
        existing_nullable=False,
    )
    op.drop_column("mpesapayments", "external_response")
    # ### end Alembic commands ###
