"""Remove DuoSession status

Revision ID: e7e28db4a558
Revises: ab9bff3f5f8b
Create Date: 2023-09-17 14:48:42.166709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7e28db4a558"
down_revision = "ab9bff3f5f8b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("duosession", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "duosession",
        sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
