"""Create PoolSessionStats model

Revision ID: f06c01aab65d
Revises: 106cbc163be1
Create Date: 2023-08-05 22:37:01.409507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f06c01aab65d"
down_revision = "106cbc163be1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poolsessionstats",
        sa.Column("total_users", sa.Integer(), nullable=True),
        sa.Column(
            "mean_pairwise_difference",
            sa.Float(),
            nullable=True,
            comment="Mean pairwise difference of the pool",
        ),
        sa.Column(
            "threshold",
            sa.Float(),
            nullable=True,
            comment="The max. percentage of people who will be paired from the pool",
        ),
        sa.Column(
            "average_score",
            sa.Float(),
            nullable=True,
            comment="The average of scores in the pool",
        ),
        sa.Column(
            "exp_weighted_moving_average",
            sa.Float(),
            nullable=True,
            comment="The exponential moving average of the pool",
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("poolsessionstats")
    # ### end Alembic commands ###
